default: &default
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: stein
  socket: /var/run/mysqld/mysqld.sock


development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root
  database: invitar_production

test:
  <<: *default
  database: invitar_test

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: stein
  database: invitar_production
 
